apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: fitverse-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: aspychalla@edu.cdv.pl
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    solvers:
    - http01:
       ingress:
         class: nginx